### ISSUE TITLE
XAuthTokenFilter throw exception

### ISSUE THREAD

**Issue by altus34** [jhipster/jhipster-sample-app-token#2]
Hi,

The XAuthTokenFilter can throw a RuntimeException.
In many case when a Runtime is triggered in this filter at the end it's an authentication issue.

So in place of returning a RuntimeException who is at a client level a 500 error
maybe we can reuse the Http401UnauthorizedEntryPoint
like

    new Http401UnauthorizedEntryPoint().commence((HttpServletRequest) req, (HttpServletResponse) resp, new BadCredentialsException(ex.getMessage(), ex)); 

who is a 401 at client level.

**Comment by jdubois** [comment]
This is just a sample app generated with JHipster, please post your ticket [on the JHipster issue tracker](https://github.com/jhipster/generator-jhipster/issues) (and please read our issue submission guidelines)
